### ISSUE TITLE
[BUG] The backdoors of the vehicle aren't open

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-truckerjob#26]
It said the rear door of the car would not open even though the car door was open.

I tried to open/close the car door again, it gave the same notification.

![ภาพหน้าจอ (6)](https://user-images.githubusercontent.com/108535266/179302110-1951b8d2-e1a8-4a8f-b49d-6cff00f59f06.png)

**Comment by spericsic** [comment]
qb-truckerjob / client / main.lua   

line 307 change to  GetVehicleDoorAngleRatio(vehicle, 2) > 0.0 and GetVehicleDoorAngleRatio(vehicle, 3) > 0.0

security fix for not be able to deliver box from trunk 

qb-truckerjob / client / main.lua 

line 534 change to :

local pos = GetEntityCoords(PlayerPedId(), true) -- S;C
local distd = #(pos - vector3(markerLocation.x, markerLocation.y, markerLocation.z)) -- S;C
if distd < 2.5 then -- S;C
Deliver()
else QBCore.Functions.Notify("Previse si udaljen", "error") end -- S:C

**Comment by GhzGarage** [comment]
Code has been updated. Thanks Spericsic
