### ISSUE TITLE
the truck wont spawn

### ISSUE THREAD

**Issue by celticgod84** [qbcore-framework/qb-truckerjob#37]
evething works marker on the map third eye the laptop but when i go to get the truck it will not spawn in takes my money to get started but never gives truck i went and changed the fuel because i use cc-fuel but still nothing and i cant find an error any where

**Comment by ahmed608** [comment]
hello can you send me the client.lua

**Comment by celticgod84** [comment]
i sent that to you any word

**Comment by DevSa1** [comment]
did you but your fuel script in client.lua ?

**Comment by twigmasters** [comment]
I am having this issue as well with no errors in the console. Any suggestions?
