### ISSUE TITLE
[Suggestion] Reputation

### ISSUE THREAD

**Issue by Krizmatic** [qbcore-framework/qb-truckerjob#4]
Please try to bring back the reputation feature. And make the trucker app work with qb-phone. So the job will be more interesting.

**Comment by darknight2590** [comment]
https://github.com/qbcore-framework/qb-truckerjob/pull/6
https://github.com/qbcore-framework/qb-phone/pull/85
if you can help for test this and thank you
@krizmatic @GhzGarage 
Source from the old official project
