### ISSUE TITLE
[BUG] attempt to index a nil value (field 'stores') lua 263

### ISSUE THREAD

**Issue by itsSayne** [qbcore-framework/qb-truckerjob#43]
**Describe the bug**
>Script Error: @qb-truckerjob/client/main.lua:263: attempt to index a nil value (field 'stores')
handler (@qb-core/client/events.lua:207)
script:qb-core SCRIPT ERROR: error object is not a string

**To Reproduce**
1. Go to Truck Storage
2. Click on any vehicle to spawn
3. Use F8 menu to get code errors; failure to identify the field 'stores'.  This is not identified anywhere else in qb-framework at all.

**Expected behavior**
Provide route and fulfill job.

**Screenshots**
**https://i.imgur.com/NuKAGEy.png**

**Questions (please complete the following information):**
 - When you last updated: 2023-01-11
 - Are you using custom resource? which ones? Jim-shops
 - Have you renamed `qb-` to something custom? no

**Additional context**
After replacing the error for the fuel script to fix, this issue arose.
I tried to see why the event wasn't registering, but after comparing the jim-shops script I noticed there is specifically a workaround
event in the resource to deny this type of error from occurring.

This issue persists the moment you grab a vehicle and try to get a route.

**Comment by Irishstevie** [comment]
Hello There I have bring this up with the dev Team <3 But update QB-shops would more and likely fix this

**Comment by r0adra93** [comment]
trucker job weas greatly improved by moving the built in shops to the actual shops in the game. update qb-shops and you will be a very happy puppy.

CLOSE THIS USELESS TICKET!
