### ISSUE TITLE
[BUG] Not Working - Not Getting Store Locations

### ISSUE THREAD

**Issue by complexza** [qbcore-framework/qb-truckerjob#47]
**Describe the bug**
Fresh install of QBCore Framework, Getting an error for Delivery Locations when starting the job.

**To Reproduce**
1. Go to 'The Trucker Location'
2. Click on a truck to use
3. See the error

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Yesterday
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Nope.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No.

**Additional context**

![FiveM_b2699_GTAProcess_Rl9boH7Z4l](https://user-images.githubusercontent.com/74205343/224514056-c114a3d4-29bb-4ae4-ae57-eb646630faa7.png)

**Comment by ShomyTKD** [comment]
Works for me on newest qb-truckerjob: https://i.imgur.com/FIaTOF2.jpeg

Error you have is reffering to `CurrentLocation.x = Config.TruckerJobLocations["stores"][location].coords.x` which means that in qb-shops you are missing `delivery` in one or more of your shops.

**Comment by complexza** [comment]
Do you get a location for delivery after the truck spawns?

**Comment by complexza** [comment]
Turns out my hunting shop didn't have a delivery location! hahahah! I feel like a idiot! Thanks for your help!
