### ISSUE TITLE
No runs past first delivery

### ISSUE THREAD

**Issue by Xinterp6196** [qbcore-framework/qb-truckerjob#48]
**Describe the bug**
> SCRIPT ERROR: @qb-truckerjob/client/main.lua: 264: attempt to index a nil value (field 'coords')
> ref (@qb-core/client/functions.lua:150)
> fn (@progressbar/client/main.lua:99)
> SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:479: attempt to concatenate a nil value (local 'err')
> fn (@progressbar/client/main.lua:99)
> SCRIPT ERROR: error object is not a string

**To Reproduce**

1. Go to Truck Storage
2. Click on any vehicle to spawn
3. Deliver to the first stop successfully
4. Script breaks at trying to point to new location
5. Use F8 menu to get code errors; failure to identify the field 'stores'. This is not identified anywhere else in qb-framework at all.

**Expected behavior**
Provide additions to the route and fulfill job.

**Screenshots**
https://i.imgur.com/9uNjhV6.png

**Questions (please complete the following information):**

- When you last updated: 2023-05-18
- Are you using custom resource? which ones? jim-mechanic, advanced_drug_creator, progressbar
- Have you renamed qb- to something custom? no

**Additional context**
When performing a route, everything acts as if it will function fine. Once delivering to the first stop, the crash happens. In order to continue, you need to return the vehicle and grab another for one stop.

**Comment by eygi** [comment]
have you already fixed this?
